apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-dev
  name: chris-store-dev
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: /chris_store:dev
    generation: null
    importPolicy: {}
    name: dev
status:
  dockerImageRepository: ""
