apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 ()
    name: ChRIS_store MySQL Database
    role: Development database
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-dev-db
  name: chris-store-dev-db
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store-dev-db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-store-dev-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: chris_store_dev
        - name: MYSQL_PASSWORD
          value: Chris1234
        - name: MYSQL_ROOT_PASSWORD
          value: rootp
        - name: MYSQL_USER
          value: chris
        image: ' '
        name: chris-store-dev-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: chris-store-dev-db-data
      restartPolicy: Always
      volumes:
      - name: chris-store-dev-db-data
        persistentVolumeClaim:
          claimName: chris-store-dev-db-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chris-store-dev-db
      from:
        kind: ImageStreamTag
        name: chris-store-dev-db:5
    type: ImageChange
status: {}
