apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 ()
    name: ChRIS_store
    role: Development server
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-dev
  name: chris-store-dev
spec:
  replicas: 1
  selector:
    io.kompose.service: chris-store-dev
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chris-store-dev
    spec:
      containers:
      - image: ' '
        name: chris-store-dev
        ports:
        - containerPort: 8010
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/store_backend
          name: chris-store-dev-claim0
      restartPolicy: Always
      volumes:
      - name: chris-store-dev-claim0
        persistentVolumeClaim:
          claimName: chris-store-dev-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - chris-store-dev
      from:
        kind: ImageStreamTag
        name: chris-store-dev:dev
    type: ImageChange
status: {}
