apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 ()
    name: ChRIS_store
    role: Development server
  creationTimestamp: null
  labels:
    io.kompose.service: chris-store-dev
  name: chris-store-dev
spec:
  ports:
  - name: "8010"
    port: 8010
    targetPort: 8010
  selector:
    io.kompose.service: chris-store-dev
status:
  loadBalancer: {}
