apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: swift-service
  name: swift-service
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: fnndsc/docker-swift-onlyone
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
