apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 ()
    name: swift
    role: swift object storage service
  creationTimestamp: null
  labels:
    io.kompose.service: swift-service
  name: swift-service
spec:
  replicas: 1
  selector:
    io.kompose.service: swift-service
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: swift-service
    spec:
      containers:
      - image: ' '
        name: swift-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /srv
          name: swift-storage
      restartPolicy: Always
      volumes:
      - name: swift-storage
        persistentVolumeClaim:
          claimName: swift-storage
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - swift-service
      from:
        kind: ImageStreamTag
        name: swift-service:latest
    type: ImageChange
status: {}
