apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 ()
    name: swift
    role: swift object storage service
  creationTimestamp: null
  labels:
    io.kompose.service: swift-service
  name: swift-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: swift-service
status:
  loadBalancer: {}
